version: "3.2"

services:

  # Subscribe default
  JavaScript-subscribe:
    container_name: js-subs
    image: 'node_recieve'
    environment:
      - MSG="Hola mundo desde js"
      - IP=127.0.0.1

  Python-subscribe:
    container_name: py-subs
    image: 'python-consumer'

  GO-subscribe:
    container_name: go-subs
    image: 'go-consumer:latest'

  # Publish default
  JavaScript-publisher:
    container_name: js-pub
    image: 'node_send'
    environment:
      - MSG="Hola mundo desde js"
      - IP=127.0.0.1

  Python-publisher:
    container_name: py-pub
    image: 'python-producer'
    environment:
      - MSG="Hola mundo desde py"
      - IP=127.0.0.1

  GO-publisher:
    container_name: go-pub
    image: 'go-producer'
    environment:
      - MSG="Hola mundo desde go"
      - IP=127.0.0.1
