version: "3.8"

services:
  #RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # Subscribe default
  JavaScript-subscribe:
    container_name: js-subs
    image: 'node_recieve'
    environment:
      - MSG="Hola mundo desde js"
      - IP=172.17.0.1

  Python-subscribe:
    container_name: py-subs
    image: 'python-consumer'

  GO-subscribe:
    image: golang:1.22
    container_name: go-rabbitmq-consumer
    working_dir: /app
    volumes:
      - ./GO/go-rabbitmq/go-consumer:/app  # Se monta la carpeta correcta dentro del contenedor
    command: go run consumer.go
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - QUEUE_NAME=test_queue
    depends_on:
      - rabbitmq

  # Publish default
  JavaScript-publisher:
    container_name: js-pub
    image: 'node_send'
    environment:
      - MSG="Hola mundo desde js"
      - IP=172.17.0.1

  Python-publisher:
    container_name: py-pub
    image: 'python-producer'
    environment:
      - MSG="Hola mundo desde py"
      - IP=127.0.0.1

  GO-publisher:
    image: golang:1.22
    container_name: go-rabbitmq-producer
    working_dir: /app
    volumes:
      - ./GO/go-rabbitmq/go-producer:/app  # Se monta la carpeta correcta dentro del contenedor
    command: go run producer.go
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - QUEUE_NAME=test_queue
    depends_on:
      - rabbitmq
